plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'maven-publish'
}

android {
    namespace 'com.leking.ads'
    compileSdk 35

    defaultConfig {
        minSdk 23
        consumerProguardFiles 'consumer-rules.pro'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }

    publishing {
        singleVariant("release") {
            withSourcesJar()
        }
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.13.1'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.multidex:multidex:2.0.1'
    implementation 'androidx.lifecycle:lifecycle-process:2.8.4'
    implementation 'com.google.android.gms:play-services-ads:23.2.0'
    implementation 'com.google.android.ump:user-messaging-platform:3.0.0'
    implementation 'com.google.firebase:firebase-analytics-ktx:22.0.2'
    compileOnly 'com.facebook.android:facebook-android-sdk:17.0.2'

    implementation 'com.facebook.shimmer:shimmer:0.5.0'
    implementation 'com.airbnb.android:lottie:6.4.1'
    implementation 'com.intuit.sdp:sdp-android:1.1.1'
    implementation 'com.intuit.ssp:ssp-android:1.1.1'
    implementation 'androidx.cardview:cardview:1.0.0'
}

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                from components.release
                groupId = 'com.github.lehongquyme'
                artifactId = 'Adsmod'
                version = '1.0.1'
            }
        }
    }
}